language: csharp
mono: none
dotnet: 2.1.4

install: 
- bash ./cicd.sh install

script:
- bash ./cicd.sh build
# - bash ./cicd.sh test

deploy:
  provider: script
  #skip_cleanup: true
  script: bash ./cicd.sh deploy
  on:
    branch: release  
    tags: true
